# Generated by Django 5.2.7 on 2025-10-18 04:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_location', models.CharField(max_length=255)),
                ('current_coordinates', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_coordinates', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('dropoff_coordinates', models.CharField(max_length=255)),
                ('current_cycle_used', models.DecimalField(decimal_places=2, max_digits=4)),
                ('route_data', models.JSONField(default=dict)),
                ('total_trip_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total_driving_hrs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stop_order', models.IntegerField()),
                ('stop_type', models.CharField(choices=[('PICKUP', 'Pickup'), ('DROPOFF', 'Dropoff'), ('FUEL', 'Fueling'), ('REST', 'Required Rest/Break (30 Min)'), ('SLEEPER', 'Sleeper Berth/Off Duty (10 Hrs)'), ('DRIVING', 'Driving Segment')], max_length=50)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('estimated_arrival', models.DateTimeField()),
                ('estimated_departure', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_routes', to='trip.trip')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['stop_order'],
            },
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_date', models.DateField()),
                ('off_duty_hrs', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('sleeper_berth_hrs', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('driving_hrs', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('on_duty_not_driving_hrs', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trip.trip')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-log_date'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'log_date'), name='unique_daily_log_per_trip')],
            },
        ),
    ]
